#!/usr/bin/env bash
# Install Delta Lake into the image and pre-resolve its jars.
#
# Run by BOTH docker/app.Dockerfile (the driver) and docker/spark.Dockerfile
# (master + workers) so the two never disagree about the Delta version.
#
# What it does:
#   1. pip-installs delta-spark alongside the already-installed pyspark. The
#      pin on pyspark is deliberate — delta-spark declares the Spark range it
#      supports, so pinning pyspark makes the resolver pick a *compatible*
#      delta-spark (or fail loudly) instead of silently downgrading Spark out
#      from under uv.lock.
#   2. writes $SPARK_CONF_DIR/spark-defaults.conf with the Delta extension,
#      catalog, and the exact maven coordinate of the installed delta-spark.
#   3. warms the ivy cache at /opt/ivy by running a trivial local job, so the
#      first real session starts instantly and works without Maven Central.
#
# WITH_DELTA=0 skips all of it: the image still runs plain Spark, and only
# memory.store's Delta backend (plus tests/test_backend_contract.py's Delta
# half, which skips itself) is unavailable.
set -euo pipefail

VENV="${VENV:-/opt/venv}"
SPARK_CONF_DIR="${SPARK_CONF_DIR:-/opt/spark-conf}"
IVY_DIR="${IVY_DIR:-/opt/ivy}"
SCALA_BINARY_VERSION="${SCALA_BINARY_VERSION:-2.13}"

mkdir -p "$SPARK_CONF_DIR" "$IVY_DIR"

# Warehouse location is shared by every image, Delta or not, so it is written
# before the early exit below.
cat > "$SPARK_CONF_DIR/spark-defaults.conf" <<CONF
# Generated by docker/spark/install_delta.sh at image build time. Edit the
# script, not this file — a rebuild overwrites it.
spark.sql.warehouse.dir /data/warehouse
CONF

if [ "${WITH_DELTA:-1}" != "1" ]; then
    echo "install_delta.sh: WITH_DELTA=${WITH_DELTA:-1}, skipping Delta Lake"
    exit 0
fi

installed_pyspark="$("$VENV/bin/python" -c \
    'import importlib.metadata as m; print(m.version("pyspark"))')"
echo "install_delta.sh: pyspark ${installed_pyspark} is installed"

if [ -n "${DELTA_SPARK_VERSION:-}" ]; then
    delta_req="delta-spark==${DELTA_SPARK_VERSION}"
else
    delta_req="delta-spark"
fi

# --python targets the venv the image already built; the pyspark pin keeps the
# locked Spark version fixed while delta-spark's own constraint picks the
# matching release.
uv pip install --python "$VENV" "$delta_req" "pyspark==${installed_pyspark}"

delta_version="$("$VENV/bin/python" -c \
    'import importlib.metadata as m; print(m.version("delta-spark"))')"
delta_package="io.delta:delta-spark_${SCALA_BINARY_VERSION}:${delta_version}"
echo "install_delta.sh: resolved ${delta_package}"

cat >> "$SPARK_CONF_DIR/spark-defaults.conf" <<CONF
spark.jars.ivy ${IVY_DIR}
spark.jars.packages ${delta_package}
spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog
CONF

# Resolve the jars now (into $IVY_DIR, which spark-defaults points every later
# session at) by running one throwaway local job.
SPARK_HOME="${SPARK_HOME:-$("$VENV/bin/python" -c \
    'import os, pyspark; print(os.path.dirname(pyspark.__file__))')}"
"$SPARK_HOME/bin/spark-submit" --master "local[1]" /opt/docker/warmup.py

# Workers and one-off `docker compose run` containers may run as a non-root
# user; the cache is read-only to them.
chmod -R a+rX "$IVY_DIR" "$SPARK_CONF_DIR"
echo "install_delta.sh: Delta ${delta_version} ready (ivy cache warmed)"
