"""Versioned prompt composition and provider-usage records."""

from __future__ import annotations

from collections import defaultdict
from enum import StrEnum

from pydantic import Field, model_validator

from ..ids import ItemId, RunId, ThreadId
from ..models import ContractModel, VersionedContract
from ..targets.models import TargetId


class MessageRole(StrEnum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


class TokenCategory(StrEnum):
    SYSTEM_STATIC = "system_static"
    STRUCTURED_SCHEMA = "structured_schema"
    TARGET_DIRECTIVE = "target_directive"
    SAS_SOURCE = "sas_source"
    BATCH_CONTEXT = "batch_context"
    REFERENCE_GUIDANCE = "reference_guidance"
    PROJECT_INSTRUCTIONS = "project_instructions"
    TASK_POLICY = "task_policy"
    THREAD_NOTES = "thread_notes"
    ROLLING_SUMMARY = "rolling_summary"
    SELECTED_HISTORY = "selected_history"
    RETRY_FEEDBACK = "retry_feedback"
    CHAT_FRAMING = "chat_framing"
    ANALYSIS_OUTPUT = "analysis_output"
    MAPPING_OUTPUT = "mapping_output"
    CODE_OUTPUT = "code_output"
    MARKDOWN_OUTPUT = "markdown_output"
    RISK_OUTPUT = "risk_output"
    RAW_OUTPUT_OVERHEAD = "raw_output_overhead"


OUTPUT_TOKEN_CATEGORIES = frozenset(
    {
        TokenCategory.ANALYSIS_OUTPUT,
        TokenCategory.MAPPING_OUTPUT,
        TokenCategory.CODE_OUTPUT,
        TokenCategory.MARKDOWN_OUTPUT,
        TokenCategory.RISK_OUTPUT,
        TokenCategory.RAW_OUTPUT_OVERHEAD,
    }
)
INPUT_TOKEN_CATEGORIES = frozenset(TokenCategory) - OUTPUT_TOKEN_CATEGORIES


class PromptMessage(ContractModel):
    role: MessageRole
    content: str = Field(min_length=1)


class PromptComponentDraft(ContractModel):
    """Attributed prompt text before it is counted by one estimator."""

    category: TokenCategory
    text: str
    message_role: MessageRole
    source_id: str | None = None
    cacheable: bool = False
    ephemeral: bool = False

    @model_validator(mode="after")
    def validate_input_category(self) -> PromptComponentDraft:
        if self.category not in INPUT_TOKEN_CATEGORIES:
            raise ValueError("prompt components must use an input token category")
        if self.category is TokenCategory.CHAT_FRAMING:
            raise ValueError("chat framing is generated by the prompt assembler")
        return self


class PromptComponent(ContractModel):
    category: TokenCategory
    text: str
    message_role: MessageRole
    token_count: int = Field(ge=0)
    source_id: str | None = None
    cacheable: bool = False
    ephemeral: bool = False


class PromptAssembly(VersionedContract):
    components: tuple[PromptComponent, ...]
    estimator: str
    encoding: str
    approximate: bool = False

    @model_validator(mode="after")
    def validate_categories(self) -> PromptAssembly:
        if any(component.category not in INPUT_TOKEN_CATEGORIES for component in self.components):
            raise ValueError("prompt assembly cannot contain output token categories")
        framing = sum(
            component.category is TokenCategory.CHAT_FRAMING
            for component in self.components
        )
        if framing > 1:
            raise ValueError("prompt assembly can contain only one chat framing component")
        return self

    def input_by_category(self) -> dict[TokenCategory, int]:
        totals: defaultdict[TokenCategory, int] = defaultdict(int)
        for component in self.components:
            totals[component.category] += component.token_count
        return dict(totals)

    @property
    def estimated_input_total(self) -> int:
        return sum(component.token_count for component in self.components)

    def render_messages(self) -> tuple[PromptMessage, ...]:
        """Render adjacent components of the same role into provider messages."""

        messages: list[PromptMessage] = []
        for component in self.components:
            if component.category is TokenCategory.CHAT_FRAMING or not component.text:
                continue
            if messages and messages[-1].role is component.message_role:
                previous = messages[-1]
                messages[-1] = PromptMessage(
                    role=previous.role,
                    content=f"{previous.content}\n\n{component.text}",
                )
            else:
                messages.append(
                    PromptMessage(role=component.message_role, content=component.text)
                )
        return tuple(messages)


class CallTokenRecord(VersionedContract):
    run_id: RunId
    thread_id: ThreadId
    item_id: ItemId
    attempt: int = Field(ge=1)
    target: TargetId
    estimator: str
    encoding: str
    approximate: bool = False
    estimated_input_by_category: dict[TokenCategory, int]
    estimated_input_total: int = Field(ge=0)
    provider_input_tokens: int | None = Field(default=None, ge=0)
    provider_output_tokens: int | None = Field(default=None, ge=0)
    provider_cache_read_tokens: int | None = Field(default=None, ge=0)
    provider_cache_write_tokens: int | None = Field(default=None, ge=0)
    provider_total_tokens: int | None = Field(default=None, ge=0)
    provider_input_delta: int | None = None
    estimated_output_by_category: dict[TokenCategory, int] = Field(default_factory=dict)
    accepted_attempt: bool = False
    recovered: bool = False

    @model_validator(mode="after")
    def validate_totals(self) -> CallTokenRecord:
        if any(
            category not in INPUT_TOKEN_CATEGORIES
            for category in self.estimated_input_by_category
        ):
            raise ValueError("estimated input counts contain an output category")
        if any(
            category not in OUTPUT_TOKEN_CATEGORIES
            for category in self.estimated_output_by_category
        ):
            raise ValueError("estimated output counts contain an input category")
        if sum(self.estimated_input_by_category.values()) != self.estimated_input_total:
            raise ValueError("estimated input category counts must sum to the total")
        expected_delta = (
            None
            if self.provider_input_tokens is None
            else self.provider_input_tokens - self.estimated_input_total
        )
        if self.provider_input_delta != expected_delta:
            raise ValueError("provider_input_delta must reconcile provider and estimated input")
        if self.provider_total_tokens is not None:
            if self.provider_input_tokens is None or self.provider_output_tokens is None:
                raise ValueError("provider total requires provider input and output counts")
            expected_total = self.provider_input_tokens + self.provider_output_tokens
            if self.provider_total_tokens != expected_total:
                raise ValueError("provider total must equal provider input plus output")
        return self

    @property
    def estimated_output_total(self) -> int:
        return sum(self.estimated_output_by_category.values())

    @property
    def accounted_total_tokens(self) -> int:
        if self.provider_total_tokens is not None:
            return self.provider_total_tokens
        return self.estimated_input_total + self.estimated_output_total


class TokenCallLedger(VersionedContract):
    """Attempt-level records aggregated without erasing discarded retries."""

    records: tuple[CallTokenRecord, ...] = Field(default_factory=tuple)

    @model_validator(mode="after")
    def validate_attempt_keys(self) -> TokenCallLedger:
        keys = [
            (record.run_id, record.thread_id, record.item_id, record.attempt)
            for record in self.records
        ]
        if len(keys) != len(set(keys)):
            raise ValueError("token call ledger contains a duplicate attempt key")
        return self

    def input_by_category(self) -> dict[TokenCategory, int]:
        totals: defaultdict[TokenCategory, int] = defaultdict(int)
        for record in self.records:
            for category, count in record.estimated_input_by_category.items():
                totals[category] += count
        return dict(totals)

    def output_by_category(self) -> dict[TokenCategory, int]:
        totals: defaultdict[TokenCategory, int] = defaultdict(int)
        for record in self.records:
            for category, count in record.estimated_output_by_category.items():
                totals[category] += count
        return dict(totals)

    @property
    def current_run_total_tokens(self) -> int:
        return sum(
            record.accounted_total_tokens
            for record in self.records
            if not record.recovered
        )

    @property
    def recovered_total_tokens(self) -> int:
        return sum(
            record.accounted_total_tokens for record in self.records if record.recovered
        )

    @property
    def retry_overhead_tokens(self) -> int:
        return sum(
            record.accounted_total_tokens
            for record in self.records
            if not record.accepted_attempt and not record.recovered
        )
